### ISSUE TITLE
Zwift docker error: no Documents folder

### ISSUE THREAD

**Issue by dumasl** [netbrain/dockerfiles#1]
Hi,

First of all thank you for you contributions and help trying to give access to zwift for unix users ! 

I have recently tried running the app through one of your docker containers but I always run into this error:

> There was an error accessing to your Documents folder. There was also an error trying to create a Zwift folder on your Desktop as a fall-back. This means Zwift can't save any files. Please contact Zwift Support.

I'm using ubuntu20.04. I've tried `latest` and `1.19.1` docker tags with no success.

Is it possible I'm facing a privilege kind of error here ? I assume I am missing something but can't find what so far. Maybe you will be able to help me resolving this issue.

Thank you for your help.

**Comment by netbrain** [comment]
Oh yes, you are probably going to need to chmod the mounted directory with
the correct permissions.

It needs to be writable by user and group of 1000.

If that doesn't work then let me know the exact command you are executing.
And I'll be happy to assist ☺️

**Comment by dumasl** [comment]
Sorry for the delay but I come here with great news since you spotted the problem perfectly ! 

The volume I mounted had the wrong goup and user ID. Setting them to 1000 solve the problem. This is just perfect. 

Thank you for your help & contributions to this.

**Comment by netbrain** [comment]
Glad to help!
